/*
 * cocoa_editor_reg.c - Harbour module registration for cocoa_editor functions
 *
 * This module registers the HB_FUNC functions defined in cocoa_editor.mm
 * so they can be found by hb_dynsymFind().
 */

#include "hbapi.h"
#include "hbinit.h"

/* Declare the functions from cocoa_editor.mm */
HB_FUNC_EXTERN( CODEEDITORRESTOREBREAKPOINTS );
HB_FUNC_EXTERN( CODEEDITORTOGGLEBREAKPOINT );
HB_FUNC_EXTERN( CODEEDITORADDBREAKPOINT );
HB_FUNC_EXTERN( CODEEDITORREMOVEBREAKPOINT );
HB_FUNC_EXTERN( CODEEDITORCLEARBREAKPOINTS );
HB_FUNC_EXTERN( CODEEDITORGETBREAKPOINTS );
HB_FUNC_EXTERN( IDE_DEBUGADDBREAKPOINT );
HB_FUNC_EXTERN( IDE_DEBUGREMOVEBREAKPOINT );
HB_FUNC_EXTERN( IDE_DEBUGCLEARBREAKPOINTS );
HB_FUNC_EXTERN( IDE_DEBUGSTART );
HB_FUNC_EXTERN( IDE_DEBUGSTART2 );
HB_FUNC_EXTERN( IDE_DEBUGRUNTOBREAK );
HB_FUNC_EXTERN( IDE_DEBUGRUNTOBREAK2 );
HB_FUNC_EXTERN( IDE_DEBUGGO );
HB_FUNC_EXTERN( IDE_DEBUGSTEP );
HB_FUNC_EXTERN( IDE_DEBUGSTEPOVER );
HB_FUNC_EXTERN( IDE_DEBUGSTOP );
HB_FUNC_EXTERN( IDE_ISDEBUGMODE );
HB_FUNC_EXTERN( IDE_DEBUGGETSTATE );
HB_FUNC_EXTERN( MAC_DEBUGPANEL );
HB_FUNC_EXTERN( IDE_ISBREAKPOINT );
HB_FUNC_EXTERN( IDE_DBGISSTEPPING );
HB_FUNC_EXTERN( IDE_DEBUGPAUSEATSTEP );
HB_FUNC_EXTERN( IDE_DBGPUMPEVENTS );
HB_FUNC_EXTERN( IDE_DBGRUNLOOPENDED );

/* Module initialization */
HB_INIT_SYMBOLS_BEGIN( hb_vm_SymbolInit_COCOA_EDITOR )
   { "CODEEDITORRESTOREBREAKPOINTS", {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORRESTOREBREAKPOINTS )}, NULL },
   { "CODEEDITORTOGGLEBREAKPOINT",   {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORTOGGLEBREAKPOINT )}, NULL },
   { "CODEEDITORADDBREAKPOINT",      {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORADDBREAKPOINT )}, NULL },
   { "CODEEDITORREMOVEBREAKPOINT",   {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORREMOVEBREAKPOINT )}, NULL },
   { "CODEEDITORCLEARBREAKPOINTS",   {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORCLEARBREAKPOINTS )}, NULL },
   { "CODEEDITORGETBREAKPOINTS",     {HB_FS_PUBLIC}, {HB_FUNCNAME( CODEEDITORGETBREAKPOINTS )}, NULL },
   { "IDE_DEBUGADDBREAKPOINT",       {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGADDBREAKPOINT )}, NULL },
   { "IDE_DEBUGREMOVEBREAKPOINT",    {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGREMOVEBREAKPOINT )}, NULL },
   { "IDE_DEBUGCLEARBREAKPOINTS",    {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGCLEARBREAKPOINTS )}, NULL },
   { "IDE_DEBUGSTART",               {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGSTART )}, NULL },
   { "IDE_DEBUGSTART2",              {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGSTART2 )}, NULL },
   { "IDE_DEBUGRUNTOBREAK",          {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGRUNTOBREAK )}, NULL },
   { "IDE_DEBUGRUNTOBREAK2",         {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGRUNTOBREAK2 )}, NULL },
   { "IDE_DEBUGGO",                  {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGGO )}, NULL },
   { "IDE_DEBUGSTEP",                {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGSTEP )}, NULL },
   { "IDE_DEBUGSTEPOVER",            {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGSTEPOVER )}, NULL },
   { "IDE_DEBUGSTOP",                {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGSTOP )}, NULL },
   { "IDE_ISDEBUGMODE",              {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_ISDEBUGMODE )}, NULL },
   { "IDE_DEBUGGETSTATE",            {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGGETSTATE )}, NULL },
   { "MAC_DEBUGPANEL",               {HB_FS_PUBLIC}, {HB_FUNCNAME( MAC_DEBUGPANEL )}, NULL },
   { "IDE_ISBREAKPOINT",             {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_ISBREAKPOINT )}, NULL },
   { "IDE_DBGISSTEPPING",            {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DBGISSTEPPING )}, NULL },
   { "IDE_DEBUGPAUSEATSTEP",         {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DEBUGPAUSEATSTEP )}, NULL },
   { "IDE_DBGPUMPEVENTS",            {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DBGPUMPEVENTS )}, NULL },
   { "IDE_DBGRUNLOOPENDED",          {HB_FS_PUBLIC}, {HB_FUNCNAME( IDE_DBGRUNLOOPENDED )}, NULL },
HB_INIT_SYMBOLS_EX_END( hb_vm_SymbolInit_COCOA_EDITOR, "cocoa_editor", 0x0, 0x0003 )